### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by hola-soy-milk** [TeamTessie/hoodietodo#3]
Some stuff for y'all to do to cleanup the repository:
- Add a [gitignore](http://git-scm.com/docs/gitignore) with the following file types to ignore:
  - The folder `node-modules`
  - The folder `data`
  - All .DS_Store files
  - All files with type `.log`
- Remove the `node-modules` folder
- Remove all `.log` files

**Comment by tamacodechi** [comment]
DONE :D
